# Copyright (C) 2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/razer/pearlyn/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/razer/pearlyn/proprietary/bin/ATFWD-daemon:system/bin/ATFWD-daemon \
    vendor/razer/pearlyn/proprietary/bin/PktRspTest:system/bin/PktRspTest \
    vendor/razer/pearlyn/proprietary/bin/StoreKeybox:system/bin/StoreKeybox \
    vendor/razer/pearlyn/proprietary/bin/adsprpcd:system/bin/adsprpcd \
    vendor/razer/pearlyn/proprietary/bin/athdiag:system/bin/athdiag \
    vendor/razer/pearlyn/proprietary/bin/btnvtool:system/bin/btnvtool \
    vendor/razer/pearlyn/proprietary/bin/btnvtool_razer:system/bin/btnvtool_razer \
    vendor/razer/pearlyn/proprietary/bin/cld-fwlog-netlink:system/bin/cld-fwlog-netlink \
    vendor/razer/pearlyn/proprietary/bin/cld-fwlog-parser:system/bin/cld-fwlog-parser \
    vendor/razer/pearlyn/proprietary/bin/cld-fwlog-record:system/bin/cld-fwlog-record \
    vendor/razer/pearlyn/proprietary/bin/cnd:system/bin/cnd \
    vendor/razer/pearlyn/proprietary/bin/cnss-daemon:system/bin/cnss-daemon \
    vendor/razer/pearlyn/proprietary/bin/cnss_diag:system/bin/cnss_diag \
    vendor/razer/pearlyn/proprietary/bin/diag_callback_client:system/bin/diag_callback_client \
    vendor/razer/pearlyn/proprietary/bin/diag_dci_sample:system/bin/diag_dci_sample \
    vendor/razer/pearlyn/proprietary/bin/diag_klog:system/bin/diag_klog \
    vendor/razer/pearlyn/proprietary/bin/diag_mdlog:system/bin/diag_mdlog \
    vendor/razer/pearlyn/proprietary/bin/diag_qshrink4_daemon:system/bin/diag_qshrink4_daemon \
    vendor/razer/pearlyn/proprietary/bin/diag_socket_log:system/bin/diag_socket_log \
    vendor/razer/pearlyn/proprietary/bin/diag_uart_log:system/bin/diag_uart_log \
    vendor/razer/pearlyn/proprietary/bin/dpmd:system/bin/dpmd \
    vendor/razer/pearlyn/proprietary/bin/dun-server:system/bin/dun-server \
    vendor/razer/pearlyn/proprietary/bin/efsks:system/bin/efsks \
    vendor/razer/pearlyn/proprietary/bin/ethtool:system/bin/ethtool \
    vendor/razer/pearlyn/proprietary/bin/ftmdaemon:system/bin/ftmdaemon \
    vendor/razer/pearlyn/proprietary/bin/hal_proxy_daemon:system/bin/hal_proxy_daemon \
    vendor/razer/pearlyn/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/razer/pearlyn/proprietary/bin/irsc_util:system/bin/irsc_util \
    vendor/razer/pearlyn/proprietary/bin/iwconfig:system/bin/iwconfig \
    vendor/razer/pearlyn/proprietary/bin/iwlist:system/bin/iwlist \
    vendor/razer/pearlyn/proprietary/bin/iwpriv:system/bin/iwpriv \
    vendor/razer/pearlyn/proprietary/bin/ks:system/bin/ks \
    vendor/razer/pearlyn/proprietary/bin/mdm_helper:system/bin/mdm_helper \
    vendor/razer/pearlyn/proprietary/bin/mdm_helper_proxy:system/bin/mdm_helper_proxy \
    vendor/razer/pearlyn/proprietary/bin/mm-pp-daemon:system/bin/mm-pp-daemon \
    vendor/razer/pearlyn/proprietary/bin/mm-qjpeg-dec-test:system/bin/mm-qjpeg-dec-test \
    vendor/razer/pearlyn/proprietary/bin/mm-qjpeg-enc-test:system/bin/mm-qjpeg-enc-test \
    vendor/razer/pearlyn/proprietary/bin/mm-qomx-idec-test:system/bin/mm-qomx-idec-test \
    vendor/razer/pearlyn/proprietary/bin/mm-qomx-ienc-test:system/bin/mm-qomx-ienc-test \
    vendor/razer/pearlyn/proprietary/bin/mpdecision:system/bin/mpdecision \
    vendor/razer/pearlyn/proprietary/bin/n_smux:system/bin/n_smux \
    vendor/razer/pearlyn/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/razer/pearlyn/proprietary/bin/nl_listener:system/bin/nl_listener \
    vendor/razer/pearlyn/proprietary/bin/oemwvtest:system/bin/oemwvtest \
    vendor/razer/pearlyn/proprietary/bin/pktlogconf:system/bin/pktlogconf \
    vendor/razer/pearlyn/proprietary/bin/port-bridge:system/bin/port-bridge \
    vendor/razer/pearlyn/proprietary/bin/ptt_socket_app:system/bin/ptt_socket_app \
    vendor/razer/pearlyn/proprietary/bin/qcks:system/bin/qcks \
    vendor/razer/pearlyn/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/razer/pearlyn/proprietary/bin/qseecom_sample_client:system/bin/qseecom_sample_client \
    vendor/razer/pearlyn/proprietary/bin/qseecomd:system/bin/qseecomd \
    vendor/razer/pearlyn/proprietary/bin/radish:system/bin/radish \
    vendor/razer/pearlyn/proprietary/bin/razerdrm:system/bin/razerdrm \
    vendor/razer/pearlyn/proprietary/bin/razerdrmcheck:system/bin/razerdrmcheck \
    vendor/razer/pearlyn/proprietary/bin/ssr_diag:system/bin/ssr_diag \
    vendor/razer/pearlyn/proprietary/bin/subsystem_ramdump:system/bin/subsystem_ramdump \
    vendor/razer/pearlyn/proprietary/bin/test_diag:system/bin/test_diag \
    vendor/razer/pearlyn/proprietary/bin/time_daemon:system/bin/time_daemon \
    vendor/razer/pearlyn/proprietary/bin/valiService:system/bin/valiService \
    vendor/razer/pearlyn/proprietary/bin/wcnss_filter:system/bin/wcnss_filter \
    vendor/razer/pearlyn/proprietary/bin/wdsdaemon:system/bin/wdsdaemon

PRODUCT_PACKAGES += \
    TimeService \
    ConnectivityExt \
    QPerformance \
    WfdCommon \
    cneapiclient \
    com.qti.dpmframework \
    com.quicinc.cne \
    dpmapi \
    oem-services \
    qcmediaplayer \
    tcmclient
